version: "3.3"

services:
  redis:
    image: redis:alpine

  beat:
    build: .
    command: "celery -A main beat"
    depends_on:
      - redis
    restart: on-failure

  celery:
    build: .
    command: "celery -A main worker -l info -P solo"
    depends_on:
      - redis
    restart: on-failure

  flower:
    build: .
    command: "celery -A main flower --address=0.0.0.0 --port=5000"
    depends_on:
      - redis
      - celery
    ports:
      - "5000:5000"
    restart: on-failure
